### ISSUE TITLE
Fails to Build

### ISSUE THREAD

**Issue by bezark** [CharlesChiuGit/Logseq-Hugo-Template#1]
Hi!
Not sure if this is an issue or if I'm doing something wrong...
Whenever I push my build fails and I get the following error:
`Push the commit or tag
  /usr/bin/git push origin gh-pages
  remote: Permission to bezark/bezark.github.io.git denied to github-actions[bot].
  fatal: unable to access 'https://github.com/bezark/bezark.github.io.git/': The requested URL returned error: 403
  Error: Action failed with "The process '/usr/bin/git' failed with exit code 128"`

Any idea what might be going on?

**Comment by charliie-dev** [comment]
You shouldn't push to `gh-pages` branch, just push to `main` branch.

**Comment by charliie-dev** [comment]
Also, please check your workflow permission.
https://github.com/ad-m/github-push-action/issues/96

**Comment by bezark** [comment]
Changing my workflow permissions totally did it! Thank you!!

**Comment by charliie-dev** [comment]
Congrats!
