### ISSUE TITLE
Why is it only showing the README file instead of the hugo site? 

### ISSUE THREAD

**Issue by turtletree** [CharlesChiuGit/Logseq-Hugo-Template#2]
Hi there, not a real issue ... more of a curiosity question. 

I'm trying to use this template. The only step I didn't follow is that - I didn't fork this repo because I already have the `username.github.io` repo setup in the past. What I did is I MANUALLY (I know it's lame, don't laugh...) copied all the files to my repo and followed some of the steps. However, it's not displaying the website correctly, it's only showing the READ.ME file if you're interested it's https://turtletree.github.io/ 

I tried again to fork the repo to a new repo and everything works much better. But I had to bear with the url looking like this https://turtletree.github.io/test-publish-logseq/ (safe to click if you're interested)

Can you give me a few tips what the reason might be for this? I'm really confused. Thank you in advance!

**Comment by turtletree** [comment]
ok I did some steps and not sure which exact step works, I think it's adding the theme again as submodules with 
`git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod`
Feel free to close... sorry about that

**Comment by charliie-dev** [comment]
Interesting, I don't think copy the repo manually is the main reason for it to fail.

> ok I did some steps and not sure which exact step works, I think it's adding the theme again as submodules with
`git submodule add --depth=1 https://github.com/adityatelange/hugo-PaperMod.git themes/PaperMod`
Feel free to close... sorry about that

Like you test it out in the second post, I do think it's related to the themes' issue.
Hugo website layout depends on the theme, but `PaperMod` itself is also a git repo, manually copying it might cause issues.
I check this [stackoverflow question](https://stackoverflow.com/questions/1811730/how-do-i-work-with-a-git-repository-within-another-repository) and see a similar solution like yours.

I'll close this issue for now, feel free to reopen it.
