### ISSUE TITLE
Github action fails on deploy

### ISSUE THREAD

**Issue by ntemple** [CharlesChiuGit/Logseq-Hugo-Template#3]
Error is:

Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2

The fix is to use actions/checkout@v3 in .github/workflows/publish.yml

**Comment by charliie-dev** [comment]
Thanks you!. Fixed in https://github.com/CharlesChiuGit/Logseq-Hugo-Template/commit/2d9d488544af6b0e1d7229394fbfb4a12ccf63db
If there's any other issues, feel free to reopen it.
