### ISSUE TITLE
不知为啥渲染不成功

### ISSUE THREAD

**Issue by karlz97** [CharlesChiuGit/Logseq-Hugo-Template#5]
我尝试了数次，包括直接fork这个仓库，不做任何修改，但是github actions执行（执行成功）后生成的网页很奇怪，内容都齐全，但是没有渲染。试了edge和chrome两个浏览器来访问，结果都一样
![image](https://user-images.githubusercontent.com/48748912/209403573-3c2b4de5-fef4-429d-b90c-b4ea4cef87f6.png)

**Comment by charliie-dev** [comment]
不好意思 能麻煩你簡單敘述一下你做過哪些嘗試嗎
只有目前資訊我有點難幫你

**Comment by karlz97** [comment]
感谢回复！我进行的尝试就是不更改任何东西，直接fork这个仓库并部署，但是仍然出现上面的情况：
1. 直接fork这个仓库
2. 等待执行Action
3. 更改pages的设定：pages->branch->gh-pages
4. 等待执行Action（Action执行成功）
5. 访问生成的网页 https://karlz97.github.io/test/ （结果如图）
您有空能否帮我试一下直接fork然后重新部署？我现在有点怀疑是不是github的问题，action执行的环境变了之类的（乱猜）。也可能我自己弄错了哪个地方但是自己没意识到。看看您重新执行action以后仍能正常渲染

**Comment by charliie-dev** [comment]
我想先確認一下
`config.yml` > `baseURL`
這行你有更改成你自己的網址嗎
https://github.com/CharlesChiuGit/Logseq-Hugo-Template#-things-you-must-modify

**Comment by karlz97** [comment]
没有！哈哈看来应该是这个问题了。我昨天第一次做的时候是成功的，后来删了仓库今天重新做就不成功了，看来不小心漏了一步。麻烦您了，谢谢！

**Comment by charliie-dev** [comment]
Nice, btw我剛剛自己重新deploy一次也是一切正常，所以template和action應該是沒有問題的。
![圖片](https://user-images.githubusercontent.com/32497323/209404955-7acd4562-831b-44f0-8719-f361807a99f0.png)

https://charleschiugit.github.io/

**Comment by karlz97** [comment]
感谢感谢！！
